ALTER TABLE rooms DISABLE ROW LEVEL SECURITY;
ALTER TABLE tenants DISABLE ROW LEVEL SECURITY;
ALTER TABLE hotel_settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE service_requests DISABLE ROW LEVEL SECURITY;
ALTER TABLE compendium_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE guest_messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE in_house_feedback DISABLE ROW LEVEL SECURITY;
